version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "main"
    reviewers:
      - "@terragon-labs"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "security"
      include: "scope"
    open-pull-requests-limit: 5
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "main"
    reviewers:
      - "@terragon-labs"
    labels:
      - "dependencies"
      - "ci-cd"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 3

# Security and vulnerability detection
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "security"
      - "critical"
    commit-message:
      prefix: "security"
    # Only for security updates
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
        update-type: "security"
