name: Security Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety pip-audit
        
    - name: Run Bandit Security Scan
      run: |
        bandit -r . -f json -o bandit-report.json || true
        
    - name: Run Safety Check
      run: |
        safety check --json --output safety-report.json || true
        
    - name: Run Pip Audit
      run: |
        pip-audit --format=json --output=pip-audit-report.json || true
        
    - name: Upload Security Reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: '*-report.json'
        
    - name: Security Summary
      run: |
        echo "## Security Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "- Bandit: Static analysis completed" >> $GITHUB_STEP_SUMMARY
        echo "- Safety: Dependency vulnerability check completed" >> $GITHUB_STEP_SUMMARY  
        echo "- Pip-audit: Package audit completed" >> $GITHUB_STEP_SUMMARY