name: Autonomous Value Discovery

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  value-discovery:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name != 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Run Enhanced Value Discovery
      run: python3 .terragon/enhanced_discovery.py
      
    - name: Update Value Backlog
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Terragon Autonomous SDLC"
        
        # Add changes if any
        git add BACKLOG.md .terragon/value-metrics.json
        
        # Commit only if there are changes
        if ! git diff --staged --exit-code; then
          git commit -m "🤖 autonomous: update value discovery backlog
          
          - Discovered new value opportunities
          - Updated prioritization based on execution history
          - Refreshed value metrics and learning data
          
          🤖 Generated with Terragon Autonomous SDLC
          
          Co-Authored-By: Claude <noreply@anthropic.com>"
          
          git push
        fi
    
    - name: Create Value Opportunity Issue
      if: github.event_name == 'schedule'
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: 1
        body: |
          ## 🎯 Autonomous Value Discovery Report
          
          **Generated**: ${{ github.event.repository.updated_at }}
          **Trigger**: Scheduled discovery cycle
          
          ### Current Priorities
          $(head -20 BACKLOG.md | tail -10)
          
          ### Ready for Autonomous Execution
          Next highest-value item ready for implementation.
          
          **Action Required**: Review and approve autonomous execution
          
          ---
          🤖 Generated by Terragon Autonomous SDLC