services:
  active-inference-api:
    build:
      context: .
      dockerfile: Dockerfile.production
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 512M
    environment:
    - ENV=production
    - LOG_LEVEL=INFO
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8080/health
      timeout: 10s
    ports:
    - 8080:8080
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    restart: unless-stopped
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  redis:
    image: redis:7-alpine
    ports:
    - 6379:6379
    restart: unless-stopped
version: '3.8'
