apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: active-inference-api
  name: active-inference-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: active-inference-api
  template:
    metadata:
      labels:
        app: active-inference-api
    spec:
      containers:
      - image: active-inference:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        name: active-inference-api
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
